on:
  push:

permissions:
  contents: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: go mod download
      - run: go mod vendor
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
